#!/usr/bin/env python

"""Read a scan file from hdhomerun_config and output several .chan files."""

import sys

SCRIPT=sys.argv[0]
scanfile = sys.argv[1]

import re

scanning = re.compile("SCANNING: ([0-9]+)")
program  = re.compile("PROGRAM ([0-9]+): (.+)")

def create_file(freq, prog, name):
	# Output to current directory for now:
	print("{0}: freq: {1} prog: {2}".format(name, freq, prog))
	filename = name + ".chan"
	f = open(filename, "w")
	f.write('NAME="' + name + '"\n')
	f.write("FREQ=" + freq + "\n")
	f.write("PROG=" + prog + "\n")
	f.close()

for line in file(scanfile): 
	match = scanning.match(line)
	if match:
		freq = match.group(1)
		continue
	# else:
	match = program.match(line)
	if match:
		prog, name = match.group(1, 2)
		create_file(freq, prog, name)

	



